class AppRoutes {
  static const String splashpages = "/SplashscreenPage";
  static const String registerapipages = "/RegisterApiPage";
  static const String loginapipages = "/LoginApiPage";
  static const String profilepages = "/ProfilePages";
  static const String homepages = "/HomePages";
  static const String favoritepages = "/FavoritePages";
  static const String mainMenuPage = "/MainMenuPage";
}
